### PR TITLE
Refactor Children's centres page

### PR DESCRIPTION
**Pull request by wellhairy**

### CODE REVIEW

**Comment by natmunckton** [comment]
Think the margin above and below the strapline in the hero might need adjusting, like on the Young people page.

**Comment by natmunckton** [comment]
I'm not sure the mixin on the H3s reducing the top margin is needed. I personally think our standard text spacing looks better.

**Comment by wellhairy** [comment]
@natmunckton the tagline here hasn't got any margin in the image or around the it so I might pick this up with you in person

**Comment by wellhairy** [comment]
@natmunckton The mixin isn't part of this work, it's something we've done to panel that should possibly only be targeting the first item first heading and not all headings under the panel but I think we need to discuss this with @LidorLapid and possibly make the change else where if it's needed.

**Pull request merged**
